language: java
jdk:
  - oraclejdk8
env:
  - SVC_DIR=config-service
  - SVC_DIR=eureka-service
  - SVC_DIR=reservation-service
  - SVC_DIR=reservation-client
script: cd $SVC_DIR && mvn clean package -DskipTests
