apiVersion: v1
kind: DeploymentConfig
metadata:
  name: reservation-service
  labels:
    app: reservation-service
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources:
  triggers:
    -
      type: ConfigChange
    -
      type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          -
            reservation-service
        from:
          kind: ImageStreamTag
          name: 'reservation-service:latest'
  replicas: 1
  selector:
    app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      containers:
        -
          name: reservation-service
          image: reservation-service
          ports:
            -
              name: app
              containerPort: 8000
              protocol: TCP
            -
              name: jolokia
              containerPort: 8778
              protocol: TCP
          env:
            -
              name: config_service
              value: http://config-service
            -
              name: eureka_service
              value: http://eureka-service/eureka
            -
              name: zipkin_service
              value: http://zipkin-service
            -
              name: SPRING_PROFILES_ACTIVE
              value: openshift
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 15
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 60
            timeoutSeconds: 1
          resources:
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30